alias rm='rm -i'
alias grep='grep --color'
alias tmux='tmux -2'
alias l='ls'
alias garmin='~/Documents/dotfiles/scripts/garmin.sh'
alias accounts='~/Documents/dotfiles/scripts/accounts.sh'
alias vim='nvim'
